aws:
  - changed-files:
    - any-glob-to-any-file: 'plugins/aws/**/*'

custom:
  - changed-files:
    - any-glob-to-any-file: 'plugins/custom/**/*'

commons:
  - changed-files:
    - any-glob-to-any-file: 'plugins/commons/**/*'

manager:
  - changed-files:
    - any-glob-to-any-file: 'plugins/manager/**/*'

logger:
  - changed-files:
    - any-glob-to-any-file: 'plugins/logger/**/*'

helpers:
  - changed-files:
    - any-glob-to-any-file: 'internal/helpers/**/*'

cli:
  - changed-files:
    - any-glob-to-any-file: 'internal/cli/**/*'

report:
  - changed-files:
    - any-glob-to-any-file: 'internal/report/**/*'

testdata:
  - changed-files:
    - any-glob-to-any-file: 'internal/testdata/**/*'

breaking-changes:
  - changed-files:
    - any-glob-to-any-file: 'plugins/commons/types.go'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'go.mod'
      - 'go.sum'

main:
  - changed-files:
    - any-glob-to-any-file: 'main.go'

makefile:
  - changed-files:
    - any-glob-to-any-file: 'Makefile'

readme:
  - changed-files:
    - any-glob-to-any-file: 'README.md'

github-actions:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/*'
