before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./
    binary: yatas
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^style'
      - '^refactor'
      - '^build'
      - '^ci'
      - '^chore(release)'

brews:
- name: yatas
  homepage: https://github.com/padok-team/yatas
  tap:
    owner: padok-team
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"  
nfpms:
  - maintainer: stan@primates.dev <stan@primates.dev>
    description: YATAS audit tool
    homepage: https://github.com/padok-team/yatas
    license: Apache 2.0
    file_name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - deb